### PR TITLE
Better env names for the deployment of Saleor Apps

### PR DESCRIPTION
**Pull request by zaiste**
The deployment to Vercel can be initiated **not only** from the marketplace (as the current env names suggest), but also from other places e.g. CLI, manually, via `git push`, etc. The names suggested here better describe the purpose of these env variables.

https://app.clickup.com/t/2549495/SALEOR-7616

### CODE REVIEW

**Comment by zaiste** [comment]
https://app.clickup.com/t/2549495/SALEOR-7616

**Comment by lkostrowski** [comment]
Waiting for approval of denver service

**Comment by lkostrowski** [comment]
@magul @zaiste please link other PRs that need to be performed/merged to make this work without serious downtimes

**Review by magul — COMMENTED** [review]
I'm on it, but it looks that change will require changes (in chronicall order, just to ensure everything is working fine across the board):
 * support for old and new variables introduced in marketplace and CLI (both in regard to deploy and register variables)
 * this one
 * changes in Klavyio (and probably Taxjar)
 * cleanup of old variables in marketplace and CLI

When I say deploy and register variables, I mean:
 * deploy stage: `SALEOR_MARKETPLACE_REGISTER_URL`/`SALEOR_REGISTER_APP_URL` and `SALEOR_MARKETPLACE_TOKEN`/`SALEOR_DEPLOYMENT_TOKEN`
 * register stage: `marketplace_token`/`token` and `envVars`/`envs`.

 * register stage:

**Review by magul — APPROVED** [review]
Tested it on newest CLI/denver and Marketplace. Working fine.

When we will move from Deno Deploy to Vercel we need to ensure it's working fine there (so will require merge of https://github.com/saleor/appraptor-node-compat/pull/2).

**Pull request merged**
